config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates_presence_of :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    comment = @post.comments.create! comments_params
    CommentsMailer.submitted(comment).deliver_later
    CommentsChannel.broadcast(comment)

    redirect_to @post
  end


  private
  def set_post
    @post = Post.find(params[:post_id])
  end

  def comments_params
    params.required(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<p> <%= comment.body %>--<%=  comment.created_at.to_s(:long) %></p>

app/views/comments/_new.html.erb
<%= form_for([ @post, Comment.new], remote: true) do |form| %>
  Your comment:<br>
  <%= form.text_area :body,size:'50x20' %><br>
  <%=form.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/first.erb
<%= form_with(model: post) do |form| %>
<html>
<head>

  <title>BLOG</title>
</head>

<body>

<button name="btn1"></button>
<%=link_to "Home", post_comment_path  %>

</body>

</html>

<% end %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<head>

  <style>
      header {
          background-color:rebeccapurple;
          color:white;
          text-align:center;
          padding:100px;
          font-size: 50px;


      }
      footer{
          background-color: chocolate;
          color: #B00100;
          text-align: center;

          border: 3px solid burlywood;
          width: 450px;
          height: 100px;
          font-size: 50px;


      }
      tbody {
          background-color:darkgray;
          color:blue;
          text-align:center;
          padding:800px;
          size: 800px;



      }
      td{

          border: 80px solid green;
          border: #ff0e0e;
          border-bottom-width: thick;

      }

      body{
          text-align:center;
          align-items: center;
          align-content: center;

      }
      table{
          text-align:center;
          align-items: center;
          align-content: center;

      }
      tr{
          text-align:center;
          align-items: center;
          align-content: center;



      }



  </style>




</head>




<body>


<header>
  <h1  style="height: 150px" >SCHOOL of LIFE</h1>
  <img src="https://www.moradam.com/wp-content/uploads/2019/10/Blog.jpg" height="500px" width="1000px">
  
</header>
<table>
  <thead>
    <tr >
      <th style="border: 6px solid red">Title</th>
      <th style="border: 6px solid red">Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td style="border : 2px solid black" width="150px" height="150px"><%= post.title %></td>
        <td style="border : 2px solid black" height="150px" width="150px"><%= post.body %></td>

        <td bgcolor="white"></td>
        <td style="border : 10px solid red" style="color: crimson" height="150px" width="150px"><%= link_to 'Show', post%></td>
        <td style="border : 10px solid red" height="150px" width="150px"><%= link_to 'Edit', edit_post_path(post) %></td>
        <td style="border : 10px solid red" height="150px" width="150px"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


</body>

<br>
<br>

<br>
<footer >
<%= link_to 'New Post', new_post_path  %>

</footer>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<br><br>




<h2>Comments</h2>
<div id="comments">
  <%= render @post.comments %>
</div>

<%= render 'comments/new', post: @post %>

</div>